### ISSUE TITLE
New FL & DP framework.

### ISSUE THREAD

**Issue by rbnuria** [weimingwill/awesome-federated-learning#1]
Hello, my name is Nuria. I'm a Ph.D. student in the University of Granada. Recently, we have released an open-source framework with FL & DP solutions in collaboration with Sherpa.AI (https://sherpa.ai/).

I would really appreciate if you take a look at it and add it to the frameworks' section

https://developers.sherpa.ai/privacy-technology/
https://github.com/sherpaai/Sherpa.ai-Federated-Learning-Framework

Here is the arXiv link to the publication (submitted and hopefully accepted soon): https://arxiv.org/abs/2007.00914

Thank you so much!!

**Comment by weimingwill** [comment]
@rbnuria Cool. I will include it.
