### ISSUE TITLE
Recommend Another 'Awesome-Federated-Learning-on-Graph-and-Tabular-Data' Repo

### ISSUE THREAD

**Issue by youngfish42** [weimingwill/awesome-federated-learning#9]
Thank you very much for organizing the Federated Learning works! ❤️

Inspired by you and other contributors, I open another repository Awesome-Federated-Learning-on-Graph-and-Tabular-Data.

I think a reorganized section on graph data, graph neural networks, and open source frameworks may be helpful and I recommend it to you here.

I highly recommend the part of the open source framework I put together ~

https://github.com/youngfish42/Awesome-Federated-Learning-on-Graph-and-Tabular-Data#federated-learning-framework

![图片](https://user-images.githubusercontent.com/38998412/180436608-3d5319e2-28d8-4199-a858-4627e4051bb6.png)

Looking forward to your visit, thanks!

**Comment by weimingwill** [comment]
Looks good.
